name: ci
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 1. clone代码
        uses: actions/checkout@v3
      - name: Set up Node # 设置node版本
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies and Build # 安装依赖并构建
        run: |
          yarn install
          yarn build
      - name: Login to Docker Hub # 2.登录Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 前面声明的用户名
          password: ${{ secrets.DOCKERHUB_TOKEN }} # 前面声明的token作为密码
      - name: Set up Docker Buildx # 3.创建Buildx的实例
        uses: docker/setup-buildx-action@v2
      - name: Build and push # 4.构建和发布
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vite:1.0.0